###
GET http://127.0.0.1:3000/ping


###
POST http://127.0.0.1:3000/products/add
Content-Type: application/json

{
  "name": "седло",
  "number": 5
}

###
POST http://127.0.0.1:3000/products/add
Content-Type: application/json

{
  "product_id": 3,
  "number": 10
}

###
POST http://127.0.0.1:3000/products/reserve
Content-Type: application/json

{
    "order_id": "abcd",
    "product_id": 2,
    "number": 50
}

###
DELETE http://127.0.0.1:3000/products/reserve
Content-Type: application/json

{
    "order_id": "abc"
}

###
POST http://127.0.0.1:3000/products/reserve
Content-Type: application/json

{
    "order_id": "abcd",
    "completed": true,
}
