@host=http://127.0.0.1:3002
###
GET {{host}}/ping


###
POST {{host}}/products/add
Content-Type: application/json

{
  "name": "седло",
  "number": 5
}

###
POST {{host}}/products/add
Content-Type: application/json

{
  "name": "уздечка",
  "number": 15
}

###
POST {{host}}/products/add
Content-Type: application/json

{
  "product_id": 1,
  "number": 10
}

###
POST {{host}}/products/reserve
Content-Type: application/json

{
    "order_id": "abcd",
    "product_id": 1,
    "number": 5
}

###
DELETE {{host}}/products/reserve
Content-Type: application/json

{
    "order_id": "abcd"
}

###
POST {{host}}/products/reserve
Content-Type: application/json

{
    "order_id": "abcd",
    "completed": true
}
