openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /products/add:
    post:
      operationId: addProduct
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        description: Created product
        required: true
    get:
      operationId: getProduct
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
        description: GET product
        required: true
  /products/reserve:
    post:
      operationId: reserveProducts
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductReserv"
        description: Created reserve product
        required: true
    delete:
      operationId: deleteReserve
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductReserv"
        description: Created reserve product
        required: true
    get:
      operationId: getReserve
      responses:
        "200":
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductReserv"
        description: GET reserve product
        required: true
components:
  schemas:
    Product:
      type: object
      properties:
        product_id:
          type: number
          format: int32
        name:
          type: string
        number:
          type: number
          format: int32
    ProductReserv:
      type: object
      properties:
        order_id:
          type: string
        product_id:
          type: number
          format: int32
        number:
          type: number
          format: int32
        completed:
          type: boolean
